# Generated by Django 2.2.6 on 2019-10-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountExtension',
            fields=[
                ('Account_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=60)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Balance', models.BigIntegerField(default=0)),
            ],
        ),
    ]
