# Generated by Django 2.2.6 on 2019-10-28 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0003_auto_20191027_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmcard',
            name='Account_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ATM.AccountExtension'),
        ),
    ]
