# Generated by Django 2.2.6 on 2019-10-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0004_auto_20191028_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmcard',
            name='Card_Status',
            field=models.CharField(max_length=50),
        ),
    ]
