# Generated by Django 2.2.6 on 2019-10-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0005_auto_20191028_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AtmMachine',
            new_name='AtMachine',
        ),
    ]
