# Generated by Django 2.2.6 on 2019-10-27 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountextension',
            name='Phone_Number',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='AtmCard',
            fields=[
                ('Atm_Card_Number', models.AutoField(primary_key=True, serialize=False)),
                ('PIN', models.IntegerField(max_length=4)),
                ('Name', models.CharField(max_length=60)),
                ('Date_Of_Issue', models.DateField(auto_now_add=True)),
                ('Expiry_Date', models.DateField(auto_now_add=True)),
                ('Address', models.CharField(max_length=100)),
                ('Two_Factor_Authentication_Status', models.BooleanField()),
                ('Phone_Number', models.CharField(max_length=20)),
                ('Card_Status', models.BooleanField()),
                ('Account_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATM.AccountExtension')),
            ],
        ),
    ]
