# Generated by Django 2.2.6 on 2019-10-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_auto_20191027_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmMachine',
            fields=[
                ('At_Machine_UID', models.AutoField(primary_key=True, serialize=False)),
                ('Current_Balance', models.DecimalField(decimal_places=0, default=0, max_digits=25)),
                ('Location', models.CharField(max_length=100)),
                ('MinimumBalance', models.DecimalField(decimal_places=0, default=0, max_digits=25)),
                ('Status', models.CharField(max_length=50)),
                ('Last_Refill_Date', models.DateField()),
                ('Next_Maintenance_Date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='accountextension',
            name='Balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='atmcard',
            name='Card_Status',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='atmcard',
            name='PIN',
            field=models.IntegerField(),
        ),
    ]
